[package]
name = "app"
version = "0.1.0"
authors = ["Sebastian Ziebell"]
repository = "https://github.com/justahero/noire-rs.git"
edition = "2018"
license = "MIT"

[dependencies]
renderer = { path = "../renderer", version = "0.1" }
window = { path = "../window", version = "0.1"}
log = "0.4.11"
