[package]
name = "renderer"
version = "0.1.0"
edition = "2018"
authors = ["Sebastian Ziebell"]
license = "MIT"

[dependencies]
wgpu   = "0.6.0"
window = { path = "../window", version = "0.1.0" }
winit  = { version = "0.22.2", package = "cart-tmp-winit", default-features = false }
